### ISSUE TITLE
_luminance() takes at most 4 arguments (14 given)

### ISSUE THREAD

**Issue by remod** [leggedrobotics/any_ping_indicator#3]
Normally, the any_ping_applet starts on system startup. If it does not and I try to start it from the console, it prints the following error:

```
remod@remod-p50:~$ any_ping_applet 
/usr/local/lib/python2.7/dist-packages/any_ping_applet/indicator.py:34: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk as gtk
/usr/local/lib/python2.7/dist-packages/any_ping_applet/indicator.py:35: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as appindicator
/usr/local/lib/python2.7/dist-packages/any_ping_applet/indicator.py:36: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify as notify
Traceback (most recent call last):
  File "/usr/local/bin/any_ping_applet", line 11, in <module>
    from any_ping_applet import indicator
  File "/usr/local/lib/python2.7/dist-packages/any_ping_applet/indicator.py", line 43, in <module>
    from . import theme
  File "/usr/local/lib/python2.7/dist-packages/any_ping_applet/theme.py", line 56, in <module>
    THEME = _get_theme()
  File "/usr/local/lib/python2.7/dist-packages/any_ping_applet/theme.py", line 52, in _get_theme
    luminance = _luminance(*pixel_rgb)
TypeError: _luminance() takes at most 4 arguments (14 given)

```

Running on Ubuntu 16.04, 4K display, scaling factor 2.

**Comment by remod** [comment]
I tracked it down to line 40 where hex is converted to int. You can use the opc if you want to reproduce the error. At the moment some lines are modified in /usr/local/lib/python2.7/dist-packages/any_ping_applet/theme.py in order to have a workaround.

**Comment by remod** [comment]
Thanks!
