### ISSUE TITLE
Runtime Error: Ensure right version and str object no attribute value

### ISSUE THREAD

**Issue by erichahn** [leggedrobotics/any_ping_indicator#4]
After installing and attempting to run the following error is present.

`any_ping_applet
/usr/local/lib/python2.7/dist-packages/any_ping_applet/indicator.py:34: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk as gtk
/usr/local/lib/python2.7/dist-packages/any_ping_applet/indicator.py:35: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as appindicator
/usr/local/lib/python2.7/dist-packages/any_ping_applet/indicator.py:36: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify as notify
no such config file
Traceback (most recent call last):
  File "/usr/local/bin/any_ping_applet", line 12, in <module>
    indicator.main()
  File "/usr/local/lib/python2.7/dist-packages/any_ping_applet/indicator.py", line 477, in main
    AnyPingIndicator().run()
  File "/usr/local/lib/python2.7/dist-packages/any_ping_applet/indicator.py", line 102, in __init__
    self.update_indicator_icon()
  File "/usr/local/lib/python2.7/dist-packages/any_ping_applet/indicator.py", line 158, in update_indicator_icon
    fig = sg.SVGFigure(str(width) + "px", "128px")
  File "/home/hahn/.local/lib/python2.7/site-packages/svgutils/transform.py", line 218, in __init__
    self._width = width.value
AttributeError: 'str' object has no attribute 'value'`

**Comment by erichahn** [comment]
Bump

**Comment by samuelba** [comment]
I don't think we will provide any update for this, since it is not compatible with Gnome, but you are welcome to do a pull request. For Gnome have a look at our new Gnome Shell extension https://github.com/ANYbotics/gnome-shell-ping-monitor-applet

**Comment by erichahn** [comment]
I am currently running normal Ubuntu 16 04

**Comment by fatestapestry** [comment]
> I don't think we will provide any update for this, since it is not compatible with Gnome, but you are welcome to do a pull request. For Gnome have a look at our new Gnome Shell extension https://github.com/ANYbotics/gnome-shell-ping-monitor-applet

what isn't compatible with gnome?

**Comment by samuelba** [comment]
All of it is not compatible with Gnome Shell Extensions and Ubuntu 16.04 has reached EOL.
